DROP DATABASE IF EXISTS todo_list;
CREATE DATABASE todo_list;
USE todo_list;
DROP TABLE IF EXISTS users;
CREATE TABLE users (
	user_id SERIAL PRIMARY KEY,
    username VARCHAR(20) UNIQUE NOT NULL,
    password VARCHAR(20) NOT NULL
);